name: Vortens/InspiredX - Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - 'fc/**'
      - 'feature/**'
      - 'release/**'
      - 'rc/**'
      - 'hotfix/**'
      - 'bugfix/**'
      - 'main'

jobs:
    deploy-prod:
      runs-on: ubuntu-latest
      timeout-minutes: 5
      steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Semantic versioning
        id: versioning
        uses: paulhatch/semantic-version@v4.0.2
        with:
          tag_prefix: "v"
          major_pattern: "break:"
          minor_pattern: "Merge"
          patch_pattern: "fix:"
          format: "${major}.${minor}.${patch}"

      - name: Create Release
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        id: version
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          title: ${{ steps.versioning.outputs.version }}
          automatic_release_tag: ${{ steps.versioning.outputs.version }}
          prerelease: false

      - name: Update Manusim
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          command_timeout: 30m
          script: | 
            cd /var/www/ksi.manusim.com.br
            ${{ secrets.SCRIPT}}
            cd src/config
            if [ -f "version.php" ]
            then
                rm version.php
            fi
            echo "<?php" >> "version.php"
            echo "\$version = \"${{  github.ref_name }}\";" >> "version.php"
            echo "Sistema Atualizado"

