name: SSH Test action
on:
  workflow_dispatch:
  push:
    branches:
      # Aqui você pode colocar as branches que disparam a pipeline
      - 'main'

jobs:
    run_example_job:
      runs-on: ubuntu-latest
      timeout-minutes: 5
      steps:
      - name: print out example job
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          command_timeout: 30m
          script: | 
            echo "Nice Job!!!"